<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Faker\Generator as Faker;
use Illuminate\Support\Str;
use App\Models\Restaurant;
use App\Models\Plate;

class PlateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(Faker $faker): void
    {

        $restaurants= Restaurant::all();
        $id_restaurant= $restaurants->pluck('id');

        $plates = [
            'plates'=>[

        // Menù ristorante 1
                [
                    "Name"=> "BURGER PROVATO",
                    "Image"=> "https://www.verosaporegreco.com/MenuDigitale/app/web/upload/products/45_2e0a0fe9afc03f8e567b3d6ee95107b2.jpg",
                    "Description"=> "Hamburger di pecora leggero e gustoso, formaggio Kasseri DOP a scaglie, salsa a scelta, pomodoro e crauti viola all’ oximeli",
                    "Price"=> "10.00",
                    'Visible'=> 1,
                    'id_restaurant' => '1',
                ],
                [
                    "Name"=> "FETA STAGIONATA AL FORNO",
                    "Image"=> "https://www.verosaporegreco.com/MenuDigitale/app/web/upload/products/1_1dd23c73d8fe69696396dd928acea1a9.jpg",
                    "Description"=> "Feta DOP stagionata in barile, impreziosita con pomodoro, peperoni, olio extra vergine di oliva e origano",
                    "Price"=> "7.50",
                    'Visible'=> 1,
                    'id_restaurant' => '1',
                ],
                [
                    "Name"=> "NTOLMADAKIA",
                    "Image"=> "https://www.verosaporegreco.com/MenuDigitale/app/web/upload/products/7_c7941eaabf858b7fbaa239cb4fdf86c9.jpg",
                    "Description"=> "Le famose foglie di vite ripiene di riso accompagnate dalla crema di ceci e tahini",
                    "Price"=> "8.00",
                    'Visible'=> 1,
                    'id_restaurant' => '1',
                ],
                [
                    "Name"=> "ORATA INTERA ALLA GRIGLIA",
                    "Image"=> "https://www.verosaporegreco.com/MenuDigitale/app/web/upload/products/28_ed8006fe36bfddcb5fc33e336565a77c.jpg",
                    "Description"=> "Orata allevata in mare aperto, alla griglia, con insalatina greca",
                    "Price"=> "18.00",
                    'Visible'=> 1,
                    'id_restaurant' => '1',
                ],
                [
                    "Name"=> "KALAMARO FRITTO",
                    "Image"=> "https://www.verosaporegreco.com/MenuDigitale/app/web/upload/products/30_60856398d4a575f42e41c29ce5c85bc6.jpg",
                    "Description"=> "Calamaro fritto con insalatina greca",
                    "Price"=> "18.00",
                    'Visible'=> 1,
                    'id_restaurant' => '1',
                ],
                [
                    "Name"=> "PITA SUVLAKI POLLO O MAIALE",
                    "Image"=> "https://www.verosaporegreco.com/MenuDigitale/app/web/upload/products/32_cc39583510797ae5b72f2501aeddd4f8.jpg",
                    "Description"=> "Pita artigianale, 2 suvlaki di maiale o di pollo, pomodoro fresco, patate fritte e origano (con 1 salsa a scelta)",
                    "Price"=> "9.00",
                    'Visible'=> 1,
                    'id_restaurant' => '1',
                ],
                [
                    "Name"=> "PEINIRLI CON LUCANICO",
                    "Image"=> "https://www.verosaporegreco.com/MenuDigitale/app/web/upload/products/42_0eec2d5b0cd92e9d786dd1de5e2b98ee.jpeg",
                    "Description"=> "Peinirli con impasto integrale, formaggio Kasseri e lucanico",
                    "Price"=> "9.00",
                    'Visible'=> 1,
                    'id_restaurant' => '1',
                ],
                [
                    "Name"=> "BAKLAVAS AL PISTACCHIO",
                    "Image"=> "https://www.verosaporegreco.com/MenuDigitale/app/web/upload/products/52_49433920ce527c352edb06f0973c6a38.jpg",
                    "Description"=> "Strati alternati di pasta fillo con pistacchio tritato e miele",
                    "Price"=> "7.00",
                    'Visible'=> 1,
                    'id_restaurant' => '1',
                ],
                [
                    "Name"=> "CREMA DI YOGURT GRECO CON MIELE E NOCI",
                    "Image"=> "https://www.verosaporegreco.com/MenuDigitale/app/web/upload/products/54_1e1ddd0e5f90620612d55fc894923de4.jpg",
                    "Description"=> "Base di yogurt greco coperto di noci e miele",
                    "Price"=> "7.00",
                    'Visible'=> 1,
                    'id_restaurant' => '1',
                ],
                [
                    "Name"=> "PITA SUVLAKI VITELLO",
                    "Image"=> "https://www.verosaporegreco.com/MenuDigitale/app/web/upload/products/34_5ea959b6c4e8a4707c73718dfb4d9f43.jpg",
                    "Description"=> "Pita artigianale, 2 suvlaki di vitello, pomodoro fresco, patate fritte e origano (con 1 salsa a scelta)",
                    "Price"=> "10.00",
                    'Visible'=> 1,
                    'id_restaurant' => '1',
                ],
        // Menù ristorante 2
                [
                    "Name" => 'TOTOPOS Y SALSA',
                    "Image" =>'https://www.beyondtheordinary.co.uk/wp-content/uploads/2020/03/Totopos-Salsa-Yucatan-Peninsula.jpg',
                    "Description"=> "Croccanti triangoli di tortillas di mais serviti con la tradizionale salsa piccante.",
                    "Price"=> "3.00",
                    'Visible'=> 1,
                    'id_restaurant' => '2',
                ],
                [
                    "Name"=> "QUESO FUNDIDO",
                    "Image"=> "https://www.budgetbytes.com/wp-content/uploads/2023/01/Queso-Fundido-V1-768x1024.jpg",
                    "Description"=> "Formaggio fuso condito con chimichurri, guarnito con guacamole",
                    "Price"=> "11.00",
                    'Visible'=> 1,
                    'id_restaurant' => '2',
                ],
                [
                    "Name"=> "NACHOS TIPICOS",
                    "Image"=> "https://www.dieta-italiana.it/wp-content/uploads/2021/05/nachos.jpg.webp",
                    "Description"=> "Croccanti triangoli di tortillas di mais guarnite con formaggio fuso, filetti di peperoni dolci e jalapeños",
                    "Price"=> "8.00",
                    'Visible'=> 1,
                    'id_restaurant' => '2',
                ],
                [
                    "Name"=> "ARRACHERA NORTENA",
                    "Image"=> "https://i0.wp.com/fridarestaurant.com/wp-content/uploads/2017/07/Arrachera.jpg?ssl=1",
                    "Description"=> "Gustoso taglio di carne tipico Messicano alla griglia. Servito con cremadi fagioli, guacamole, pico de gallo e ensalada de Nopales",
                    "Price"=> "21.00",
                    'Visible'=> 1,
                    'id_restaurant' => '2',
                ],
                [
                    "Name"=> "CARNE alla TAMPIQUENA ",
                    "Image"=> "https://labamba123.com/wp-content/uploads/2020/06/ADS_6274.jpg",
                    "Description"=> "Trancio di carne alla griglia accompagnato con enmolada, riso messicano, guacamole, queso panela, nopales e pico de gallo",
                    "Price"=> "21.00",
                    'Visible'=> 1,
                    'id_restaurant' => '2',
                ],
                [
                    "Name"=> "QUESADILLAS",
                    "Image"=> "https://assets.tmecosys.com/image/upload/t_web600x528/img/recipe/ras/Assets/218ab89b376ede5df04d94be8ff6fba8/Derivates/2f294361010f967d642a65eee061cd2c51f7fcbf.jpg",
                    "Description"=> "Grande tortilla di farina ripiena di Formaggio e a scelta con: Tinga poblana - Picadillo - Chili con carme - Vegetariana",
                    "Price"=> "13.00",
                    'Visible'=> 1,
                    'id_restaurant' => '2',
                ],
                [
                    "Name"=> "ENCHILADAS VERDES",
                    "Image"=> "https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.mexicoinmykitchen.com%2Fwp-content%2Fuploads%2F2022%2F11%2FEnchiladas-verdes-2.jpg&tbnid=QEZ9iWjXua_ttM&vet=12ahUKEwic55Xa7KSBAxUpy7sIHXl6AyUQMygFegQIARBg..i&imgrefurl=https%3A%2F%2Fwww.mexicoinmykitchen.com%2Fswiss-green-enchiladas%2F&docid=2yF1yHsSBzPTyM&w=1200&h=1800&q=ENCHILADAS%20VERDES&client=firefox-b-d&ved=2ahUKEwic55Xa7KSBAxUpy7sIHXl6AyUQMygFegQIARBg",
                    "Description"=> "Tre tortillas di mais ripiene di pollo, ricoperte di salsa verde, guarnite con formaggio fresco. Accompagnate con frijoles aguado e riso mex",
                    "Price"=> "14.00",
                    'Visible'=> 1,
                    'id_restaurant' => '2',
                ],
                [
                    "Name"=> "BURRITO",
                    "Image"=> "https://www.fattoincasadabenedetta.it/wp-content/uploads/2023/02/Burrito0105.jpg",
                    "Description"=> "Tortillas di farina ripiena a scelta con pollo, peperoni cipolla e formaggio, manzo e formaggio o vegetariana, accompagnato con riso mex e fagioli interi",
                    "Price"=> "15.00",
                    'Visible'=> 1,
                    'id_restaurant' => '2',
                ],
                [
                    "Name"=> "TACOS",
                    "Image"=> "https://primochef.it/wp-content/uploads/2023/03/SH_tacos_con_carne-640x350.jpg.webp",
                    "Description"=> "Tre tortillas di mais ripiene con: Manzo, Chorizo o Campechano. Servite con pico de gallo, guacamole e lime",
                    "Price"=> "14.00",
                    'Visible'=> 1,
                    'id_restaurant' => '2',
                ],
                [
                    "Name"=> "JALAPEÑOS",
                    "Image"=> "https://cgmsurgelati.it/wp-content/uploads/2020/05/5.cgm-surgelati-happyhour-jalapenos-verdi-formaggio.jpg",
                    "Description"=> "Peperoncini messicani verdi picanti",
                    "Price"=> "3.00",
                    'Visible'=> 1,
                    'id_restaurant' => '2',
                ],

            //Menù ristorante 3
                [
                    "Name"=> "Croissant Salato con Crudo e fontina",
                    "Image"=> "https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/Croissant-Salati-5-ricette.jpg?itok=Y59gt9WB",
                    "Description"=> "Croissant multisemi, prosciutto crudo, fontina, songino",
                    "Price"=> "5.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "3"
                ],
                [
                    "Name"=> "Tramezzino Salmone e Avocado",
                    "Image"=>  "https://blogdilifestyle.it/wp-content/uploads/2019/09/tartine-al-salmone.jpg",
                    "Description"=>  "Morbido pane per tramezzini con un gustoso ripieno di Salmone e Avocado",
                    "Price"=>  "6.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "3",
                ],
                [
                    "Name"=> "Crêpes nutella",
                    "Image"=>  "https://www.gustissimo.it/articoli/ricette/dolci-dessert/crepes-alla-nutella-e-panna-montata.jpg",
                    "Description"=>  "Un sottile velo di deliziosa crema alle nocciole e al cacao su un impasto di latte e farina",
                    "Price"=>  "5.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "3",
                ],
                [
                    "Name"=> "Tramezzino Porchetta Arrosto e Funghi",
                    "Image"=> "https://blog.giallozafferano.it/cucinoperpassione/wp-content/uploads/2020/07/tramezzini-prosciutto-e-funghi.jpg",
                    "Description"=> "Morbido pane per tramezzini con un gustoso ripieno di Porchetta Arrosto e Funghi",
                    "Price"=> "6.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "3",
                ],
                [
                    "Name"=> "Bagel con Salmone",
                    "Image"=> "https://media.soscuisine.com/images/recettes/large/1371.jpg",
                    "Description"=> "Pane bagel di pasta bretzel decorato con semi di sesamo farcito con salmone affumicato norvegese, salsa panna acida e erba cipollina, songino",
                    "Price"=> "8.50",
                    'Visible'=> 1,
                    "id_restaurant"=> "3",
                ],
                [
                    "Name"=> "Insalata Pollo e Formaggio",
                    "Image"=> "https://www.ricettasprint.it/wp-content/uploads/2021/01/Insalata-di-pollo-con-formaggio-ricettasprint.jpg",
                    "Description"=> "Insalatona Pollo e Formaggio",
                    "Price"=> "6.90",
                    'Visible'=> 1,
                    "id_restaurant"=> "3",
                ],
                [
                    "Name"=> "Insalata Tonno e Feta",
                    "Image"=> "https://primochef.it/wp-content/uploads/2022/07/SH_insalata_di_feta_e_tonno.jpg.webp",
                    "Description"=> "Insalatona Tonno, feta DOP e Crostini",
                    "Price"=> "6.90",
                    'Visible'=> 1,
                    "id_restaurant"=> "3",
                ],
                [
                    "Name"=> "Schiacciatina Cotoletta Plant Based",
                    "Image"=> "https://s3.eu-central-1.amazonaws.com/quomi/media/182241/conversions/Panino-con-la-cotoletta-thumb-big.jpg",
                    "Description"=> "Focaccia, Cotoletta Plant Based, Insalata, Pomodoro e maionese vegana",
                    "Price"=> "7.50",
                    'Visible'=> 1,
                    "id_restaurant"=> "3",
                ],
                [
                    "Name"=> "Triple Chocolate Muffin",
                    "Image"=> "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/de14ea96-8907-469f-8eb2-28aee89e19da/Derivates/fb448ec3-addf-4639-94b9-d1fd0b3c43c9.jpg",
                    "Description"=> "Gustoso muffin con cioccolato fondente, al latte e bianco ripieno di cioccolato fondente",
                    "Price"=> "3.50",
                    'Visible'=> 1,
                    "id_restaurant"=> "3",
                ],
                [
                    "Name"=> "Donut Cioccolato",
                    "Image"=> "https://www.sangiorgiospa.eu/wp-content/uploads/2022/01/D1570-Donut-cioccolato.jpeg",
                    "Description"=> "Donut classico ricoperto da cioccolato al latte e decorato con granella di cioccolato al latte",
                    "Price"=> "2.90",
                    'Visible'=> 1,
                    "id_restaurant"=> "3",
                ],
        // Menù ristorante 4
                [
                    "Name" => 'Pad thai - yasai | Veg',
                    "Image" =>'https://img.taste.com.au/z9EIVHJg/taste/2021/02/10-minute-vegetarian-pad-thai-168946-2.jpg',
                    "Description"=> "Noodles di riso in salsa amai con germogli, porri, chilli e cipolla rossa, guarnizione con scalogno fritto, menta e lime fresco. Le uova sono state eliminate da questo piatto per renderlo idoneo alla dieta vegana.",
                    "Price"=> "14.10",
                    'Visible'=> 1,
                    'id_restaurant' => '4',
                ],
                [
                    "Name"=> "Shao mai - 4 pezzi",
                    "Image"=> "https://www.esushi.it/wp-content/uploads/2022/04/RA_8240.jpg",
                    "Description"=> "ravioli cotti al vapore, con ripieno di carne; guarniti con carne tritata finemente alla quale è aggiunto nell'impasto sherry, aglio e cipolline.",
                    "Price"=> "5.00",
                    'Visible'=> 1,
                    'id_restaurant' => '4',
                ],
                [
                    "Name"=> "Riso saltato con gamberi",
                    "Image"=> "https://www.frigomagazine.com/wp-content/uploads/2016/01/RISO-SALTATO-CON-VERDURE-E-GAMBERI.jpg",
                    "Description"=> "Riso integrale, cucinato a cottura lenta con gamberi e sfumati con vino bianco",
                    "Price"=> "8.50",
                    'Visible'=> 1,
                    'id_restaurant' => '4',
                ],
                [
                    "Name"=> "Riso al curry",
                    "Image"=> "https://www.casapappagallo.it/storage/19281/riso-al-curry-con-verdure.JPG",
                    "Description"=> "In questa ricetta questa spezia diventa l'ingrediente di un primo piatto aromatico e gustoso: il curry.",
                    "Price"=> "6.00",
                    'Visible'=> 1,
                    'id_restaurant' => '4',
                ],
                [
                    "Name"=> "Teriyaki donburi - Manzo",
                    "Image"=> "https://www.datocms-assets.com/41342/1614679046-waga-donburi-chicken.webp?auto=format&fm=png&lossless=true",
                    "Description"=> "manzo. salsa teriyaki. riso bianco. carote. songino, cipolla rossa e cipollotto, semi di sesamo. contorno di kimchee",
                    "Price"=> "14.90",
                    'Visible'=> 1,
                    'id_restaurant' => '4',
                ],
                [
                    "Name"=> "Bao Buns Maiale",
                    "Image"=> "https://images.dissapore.com/wp-content/uploads/2018/02/panini-cinesi-al-vapore-800x531.jpg",
                    "Description"=> "Pancia di maiale, mela con impanatura panko, sriracha, maionese e coriandolo",
                    "Price"=> "7.30",
                    'Visible'=> 1,
                    'id_restaurant' => '4',
                ],
                [
                    "Name"=> "Edamame | Veg",
                    "Image"=> "https://www.my-personaltrainer.it/2020/04/23/edamame_900x760.jpeg",
                    "Description"=> "fagioli con sale",
                    "Price"=> "4.80",
                    'Visible'=> 1,
                    'id_restaurant' => '4',
                ],
                [
                    "Name"=> "Shirodashi pork belly ramen",
                    "Image"=> "https://i0.wp.com/www.sprinklesandseasalt.com/wp-content/uploads/2018/12/Instant-Pot-Pork-Belly-Ramen.jpg?resize=640%2C427&ssl=1",
                    "Description"=> "Pancia di maiale cotta lentamente, ramen noodles, menma, cipollotto, wakame, salsa barbecue coreana, mezzo uovo marinato al tè, ricco brodo di pollo con dashi e miso",
                    "Price"=> "14.90",
                    'Visible'=> 1,
                    'id_restaurant' => '4',
                ],
                [
                    "Name"=> "Ginger cheesecake",
                    "Image"=> "https://static01.nyt.com/images/2017/12/11/dining/11COOKING-GINGERBREADCHEESECAKE2/11COOKING-GINGERBREADCHEESECAKE2-articleLarge.jpg",
                    "Description"=> "Ginger cheescake servita con topping al caramello",
                    "Price"=> "6.30",
                    'Visible'=> 1,
                    'id_restaurant' => '4',
                ],
                [
                    "Name"=> "Chocolate Cake",
                    "Image"=> "https://www.thespruceeats.com/thmb/SOVTa4Gj8J1nBcIAov0BLbrZX_A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/one-bowl-chocolate-cake-4134342-hero-01-d0a3e9d7d1b342d9963492b08bbcdf84.jpg",
                    "Description" => "torta al cioccolato, servita con gelato alla vaniglia. togli il gelato per rendere questo piatto vegano",
                    "Price"=> "6.30",
                    'Visible'=> 1,
                    'id_restaurant' => '4',
                ],
    // Menù ristorante 5
                [
                    "Name"=> "Spaghetti allo scoglio",
                    "Image"=>"https://cdn.cook.stbm.it/thumbnails/ricette/40/40439/hd1600x900.jpg",
                    "Description"=> "Deliziosi spaghetti alla chitarra artigianali, arricchiti con frutti di mare e gamberi",
                    "Price"=> "20.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "5",
                ],
                [
                    "Name"=> "Ziti alla genovese",
                    "Image"=>"https://blog.giallozafferano.it/dulcisinforno/wp-content/uploads/2023/02/Ziti-alla-genovese-2107.jpg",
                    "Description"=> "Ziti spezzati come da tradizione napoletana, conditi con sugo di carne e cipolle stracotti",
                    "Price"=> "15.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "5",
                ],
                [
                    "Name"=>"Spaghetti alle vongole",
                    "Image"=> "https://www.barilla.com//-/media/images/it_it/recipes/pesti/spaghetti_nerano_pesto_genovese.jpg",
                    "Description"=> "Spaghettoni quadrati in bianco con vongole e prezzemolo",
                    "Price"=> "18.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "5",
                ],
                [
                    "Name"=> "Pasta Fagioli e Cozze",
                    "Image"=>"https://it.rc-cdn.community.thermomix.com/recipeimage/4dptblj5-79fec-197803-d2121-e2qm5m2a/d716a616-9ed3-4ef0-9101-1ca429cdca18/large/pasta-fagioli-e-cozze.jpg",
                    "Description"=> "Pasta mista condita con fagioli, cozze e sedano",
                    "Price"=> "13.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "5",
                ],
                [
                    "Name"=> "Pasta e Piselli",
                    "Image"=> "https://www.youcookit.net/it/wp-content/uploads/2021/05/pasta-e-piselli-13.jpg",
                    "Description"=> "Tubetti rigati serviti con cipolla, piselli e pancetta",
                    "Price"=> "12.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "5",
                ],
                [
                    "Name"=> "Grigliata mista di Terra",
                    "Image"=> "https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2023/04/Grigliata-di-carne.jpg",
                    "Description"=> "Due salsicce, due petti di pollo e due hamburger cotti alla griglia e serviti con patate al forno e verdura.Consigliato per due persone ",
                    "Price"=> "25.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "5",
                ],
                [
                    "Name"=> "Grigliata mista di Mare",
                    "Image"=>"https://wips.plug.it/cips/buonissimo.org/cms/2012/10/grigliata-mista-di-pesce-6.jpg",
                    "Description"=> "Gamberoni, calamari, polpo e pesce spada cotti alla griglia e serviti con verdura e insalata.Consigliata per due persone",
                    "Price"=> "35.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "5",
                ],
                [
                    "Name"=> "Cuoppo misto Mare",
                    "Image"=>"https://www.giallozafferano.it/images/189-18991/Cuoppo-di-mare-con-mayo-al-mojito_780x520_wm.jpg",
                    "Description"=> "Frittura di gamberi,calamari e alici ",
                    "Price"=> "18.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "5",
                ],
                [
                    "Name"=> "Patate al forno",
                    "Image"=>"https://www.buttalapasta.it/wp-content/uploads/2016/09/patate-al-forno.jpg",
                    "Description"=> "Contorno di patate cotte al forno con rosmarino",
                    "Price"=> "5.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "5",
                ],
                [
                    "Name"=> "Acqua Naturale",
                    "Image"=>"https://lnx.savia.it/80-home_default/acqua-naturale-1-litro.jpg",
                    "Description"=> "Bottiglia di acqua naturale da 1L",
                    "Price"=> "3.00",
                    'Visible'=> 1,
                    "id_restaurant"=> "5",
                ],

        // Menù ristorante 6
                [
                    "Name" => "Lasagne  vegetariane",
                    "Image" =>"https://www.galbani.it/sites/default/files/styles/width_1110/public/lasagne-vegetariane_big.jpg?itok=tpf5YOOh",
                    "Description"=> "Vi proponiamo, infatti, la realizzazione delle lasagne vegetariane, che accompagnano deliziosi ortaggi con una morbida e deliziosa salsa besciamella.",
                    "Price"=> "7.00",
                    'Visible'=> 1,
                    'id_restaurant' => '6',
                ],
                [
                    "Name"=> "Polpette vegetariane",
                    "Image"=> "https://www.galbani.it/sites/default/files/styles/width_1110/public/polpette_vegetariane_Big.jpg?itok=Yy3xUNGn",
                    "Description"=> "Le polpette vegetariane sono una preparazione molto golosa; sono anche un modo simpatico per far mangiare la verdura ai bambini* poiché rimanendo ben celata può essere apprezzata anche dai più piccoli!",
                    "Price"=> "8.50",
                    'Visible'=> 1,
                    'id_restaurant' => '6',
                ],
                [
                    "Name"=> "Melanzane ripiene di mozzarella",
                    "Image"=> "https://www.galbani.it/sites/default/files/styles/width_1110/public/melanzaneripienemozz.jpg?itok=guJjKtW_",
                    "Description"=> "Se siete alla ricerca di un secondo piatto leggero e facile da preparare, vi consigliamo le melanzane ripiene vegetariane",
                    "Price"=> "6.00",
                    'Visible'=> 1,
                    'id_restaurant' => '6',
                ],
                [
                    "Name"=> "Peperoni ripieni vegetariani",
                    "Image"=> "https://www.galbani.it/sites/default/files/vegetariane_top10_big.jpg",
                    "Description"=> "I peperoni ripieni sono uno dei piatti forti della cucina italiana, in particolare meridionale. Il sapore e il carattere di questa ricetta sono noti a tutti, nonché l'ampia possibilità di variare il ripieno in maniera creativa e in base a quanto si ha a disposizione in frigo.",
                    "Price"=> "8.00",
                    'Visible'=> 1,
                    'id_restaurant' => '6',
                ],
                [
                    "Name"=> "Spaghetti con le zucchine e ricotta",
                    "Image"=> "https://www.galbani.it/sites/default/files/styles/width_1110/public/spaghetti_con_zucchine_big.jpg?itok=BpnDhmQZ",
                    "Description"=> "Le verdure di stagione ci aiutano sempre a preparare ottimi piatti. Dai peperoni alle melanzane, dalle cipolle al pomodoro, dalla zucca alle zucchine e da queste a molti altri ortaggi, le verdure sono sempre ottime alleate in cucina!",
                    "Price"=> "8.00",
                    'Visible'=> 1,
                    'id_restaurant' => '6',
                ],
                [
                    "Name"=> "Pasta al forno vegetariana",
                    "Image"=> "https://www.galbani.it/sites/default/files/styles/width_1110/public/pasta_forvo_vegetariana_big.jpg?itok=50U0LiTL",
                    "Description"=> "Un sapore fresco di verdure per una ricetta di un primo piatto davvero stuzzicante. È la pasta al forno vegetariana, una pietanza colorata oltre che gustosa, che si realizza impiegando verdure di stagione.",
                    "Price"=> "8.00",
                    'Visible'=> 1,
                    'id_restaurant' => '6',
                ],
                [
                    "Name"=> "Pomodori ripieni",
                    "Image"=> "https://www.galbani.it/sites/default/files/styles/width_1110/public/pomodori_ripieni_big2.jpg?itok=9XW-Ux1e",
                    "Description"=> "Rispetto alle più diffuse ricette di piatti freddi che vedono i pomodori ripieni di riso",
                    "Price"=> "7.50",
                    'Visible'=> 1,
                    'id_restaurant' => '6',
                ],
                [
                    "Name"=> "Hummus di edamame e piselli",
                    "Image"=> "https://www.cucchiaio.it/content/dam/cucchiaio/it/ricette/2023/07/hummus-di-edamame-e-piselli/Hummus_edamame_piselli_orizz.jpg",
                    "Description"=> "Una ricetta che è una vera sorpresa. Si prepara in 20 minuti, 10 per cuocere edamame e piselli e 10 per frullare e servire il tutto con una decorazione di pomodori dai colori che preferite e crostoni di pani abbrustolito per spalmarci il gustoso hummus. ",
                    "Price"=> "7.50",
                    'Visible'=> 1,
                    'id_restaurant' => '6',
                ],
                [
                    "Name"=> "Risotto al radicchio",
                    "Image"=> "https://www.galbani.it/sites/default/files/styles/width_1110/public/risotto_radicchio_980.jpg?itok=iZCctkxr",
                    "Description"=> "Il re della vostra tavola di oggi sarà il riso, la regina sarà invece l'arte con cui si dà vita ai risotti",
                    "Price"=> "8.50",
                    'Visible'=> 1,
                    'id_restaurant' => '6',
                ],
                [
                    "Name"=> "Torta salata vegetariana",
                    "Image"=> "https://www.galbani.it/sites/default/files/styles/width_1110/public/torta_salata_vegetariana980.jpg?itok=qXpNfCnP",
                    "Description"=> "La ricetta che vi proponiamo in questa pagina è quella di una pietanza davvero saporita che farà felice i vegetariani e non solo",
                    "Price"=> "8.50",
                    'Visible'=> 1,
                    'id_restaurant' => '6',
                ],
      // Menù ristorante 7          
                [
                    "Name"=>"Napoli",
                    "Image"=>"https://semplice.us/wp-content/uploads/2021/01/PIZZA-NAPOLI-800x533.jpg",
                    "Description"=>"Questa pizza nasce da ingredienti semplici che ci riportano indietro nel tempo: pomodoro, origano e acciughe ne fanno una pizza dal gusto ricco e corposo, trasformando una ricetta genuina in una carta vincente che rientra a pieno titolo nell’Olimpo delle pizze più amate di tutti i tempi. A differenza della pizza Margherita è realizzata senza l’aggiunta della mozzarella, quindi adatta anche a chi è intollerante al lattosio.",
                    "Price"=> "7.00",
                    'Visible'=> 1,
                    "id_restaurant"=>"7",
                ],
                [
                    "Name"=>"Capricciosa",
                    "Image"=>"https://semplice.us/wp-content/uploads/2021/01/pizza-capricciosa-1-800x533.jpg",
                    "Description"=>"Questa tipica pizza della tradizione culinaria italiana è, come ne suggerisce il nome, così ricca di condimento da avere un aspetto stravagante e goloso. La sua ricetta a base di pomodoro, mozzarella, funghi, prosciutto cotto, olive e carciofini, la rende senza alcun dubbio la pizza più ricca in assoluto e adatta a soddisfare anche l’appetito più grande!",
                    "Price"=>"8.50",
                    'Visible'=> 1,
                    "id_restaurant"=>"7",
                ],
                [
                    "Name"=>"Marinara",
                    "Image"=>"https://semplice.us/wp-content/uploads/2021/01/pizza-marinara.jpg",
                    "Description"=>"Questa pizza semplice, che deve il suo nome ai pasti frugali a base di pizza fatta con ingredienti facilmente conservabili che accompagnavano un tempo i marinai, è a base di ingredienti molto semplici e di ottima qualità insieme danno vita ad un capolavoro del gusto. Il suo aroma un po’ pungente, dovuto all’incontro di aglio, pomodoro, olio extra-vergine di oliva e origano, è particolare, fragrante e digeribile. Adatta a tutti i palati!",
                    "Price"=>"6.00",
                    'Visible'=> 1,
                    "id_restaurant"=>"7",
                ],
                [
                    "Name"=>"Bufalina",
                    "Image"=>"https://semplice.us/wp-content/uploads/2021/01/PIZZA-BUFALINA-800x533.jpg",
                    "Description"=>"Assaggiare una pizza Bufalina non ha prezzo! La mozzarella di bufala, a cui deve il nome, le dona un gusto pieno e corposo, mentre la salsa di pomodoro e gli aromi, in particolare basilico e origano, completano l’esperienza lasciando in bocca un sapore intenso e prolungato. Imperdibile per i veri amanti della pizza napoletana!",
                    "Price"=>"8.00",
                    'Visible'=> 1,
                    "id_restaurant"=>"7",
                ],
                [
                    "Name"=>"Boscaiola",
                    "Image"=>"https://semplice.us/wp-content/uploads/2021/01/PIZZA-BOSCAIOLA-800x533.jpg",
                    "Description"=>"La pizza alla boscaiola è una pizza bianca tra le più soffici e golose. Tipica della cucina napoletana, i suoi ingredienti sono di alta qualità e le danno un tocco rustico molto particolare. A base di funghi champignon, salsicce, prezzemolo, aglio, aromi e olio extra-vergine d’oliva, il tutto ricoperto da un generoso strato di mozzarella, è una delizia per il palato che sorprende ad ogni morso.",
                    "Price"=>"8.00",
                    'Visible'=> 1,
                    "id_restaurant"=>"7",
                ],
                [
                    "Name"=>"Ai Quattro Formaggi",
                    "Image"=>"https://semplice.us/wp-content/uploads/2021/01/pizza-ai-4-formaggi-800x661.jpg",
                    "Description"=>"La pizza ai Quattro Formaggi è davvero un classico che non manca mai nelle pizzerie italiane. Un vero e proprio must per gli amanti del formaggio in tutte le sue versioni. Il gusto ricco ed eccezionale compensa il fatto che questa pizza golosissima non rientri tra le più indicate per la linea! E’ sicuramente tra le pizze più sfiziose che possiamo trovare sulle nostre tavole!",
                    "Price"=>"8.00",
                    'Visible'=> 1,
                    "id_restaurant"=>"7",
                ],
                [
                    "Name"=>"Romana",
                    "Image"=>"https://semplice.us/wp-content/uploads/2021/01/pizza-romana-1-800x533.jpg",
                    "Description"=>"Cerchi una variante della pizza napoletana più verace? Allora non puoi perderti la pizza romana, a base di pomodoro, acciughe, origano, mozzarella e olio extra-vergine di oliva. E’ una gustosa pizza croccante fuori e con un centro morbido e allettante. Sottile e scrocchiarella, la sua ricetta semplice e allo stesso tempo stuzzicante la rende irresistibile!",
                    "Price"=>"7.50",
                    'Visible'=> 1,
                    "id_restaurant"=>"7",
                ],
                [
                    "Name"=>"Alla Diavola",
                    "Image"=>"https://semplice.us/wp-content/uploads/2021/01/pizza-diavola-800x564.jpg",
                    "Description"=>"Questa pizza dal carattere forte è perfetta per i palati più coraggiosi! A base di ingredienti molto piccanti, che devono letteralmente bruciare in bocca, ha un sapore vivace e deciso. Gli ingredienti di base sono peperoncino e salame piccante, che rendono questa tradizionale ricetta classica un piatto semplice per gli amanti dei gusti piccanti.",
                    "Price"=>"7.50",
                    'Visible'=> 1,
                    "id_restaurant"=>"7",
                ],
                [
                    "Name"=>"Carrettiera",
                    "Image"=>"https://semplice.us/wp-content/uploads/2021/01/pizza-salsiccia-800x533.jpg",
                    "Description"=>"Questa pizza dal gusto particolare e delizioso, famosissima a Napoli, prende il suo nome dal carro un tempo tirato dai carrettieri che consumavano i friarelli, (broccoletti), al termine del loro faticoso lavoro. Il resto degli ingredienti che accompagnano questo capolavoro della tradizione culinaria italiana sono salsicce, provola affumicata, peperoncino e aglio, per un gusto intenso e indimenticabile.",
                    "Price"=>"8.50",
                    'Visible'=> 1,
                    "id_restaurant"=>"7",
                ],
                [
                    "Name"=>"Valtellina",
                    "Image"=>"https://www.pizzeriagraniantichi.it/templates/yootheme/cache/01/pizza-valtellina-01e05d2a.webp",
                    "Description"=>"La pizza valtellina è una pizza leggera ma allo stesso tempo ricca di gusto. Preparata con salsa di pomodoro, mozzarella fior di latte, bresaola, rucola e grana, è la soluzione ideale per tutti quelli che hanno voglia di mangiare una pizza nutriente ma allo stesso tempo leggera.",
                    "Price"=>"8.50",
                    'Visible'=> 1,
                    "id_restaurant"=>"7",
                ],

    // Menù ristorante 8
                [
                    "Name" => 'BACON KING 3.0',
                    "Image" =>'https://www.burgerking.it/site/assets/files/8495654/prodotto_copia_3.png',
                    "Description"=> "L'evoluzione del Bacon King 3 strati di carne alla griglia, 3 strati di formaggio e 8 fette di delizioso bacon.",
                    "Price"=> "8.30",
                    'Visible'=> 1,
                    'id_restaurant' => '8',
                ],
                [
                    "Name"=> "WHOPPER",
                    "Image"=> "https://www.burgerking.it/site/assets/files/1046/whopper-1.jpg",
                    "Description"=> "La ricetta del leggendario WHOPPER® non è cambiata. La succosa carne di manzo alla griglia e gli ingredienti freschi ti garantiscono un sapore ineguagliabile. Naturalmente viene sempre preparato al momento per te – proprio come ti piace di più. È bello che certe cose non cambino mai.",
                    "Price"=> "6.70",
                    'Visible'=> 1,
                    'id_restaurant' => '8',
                ],
                [
                    "Name"=> "DOUBLE CHEESE BACON",
                    "Image"=> "https://www.burgerking.it/site/assets/files/1786/double-cheese-bacon_imgprodotto.jpg",
                    "Description"=> "Per i non conformisti per natura, questo hamburger ha tutto. Doppio hamburger, formaggio cheddar e bacon. Cosa puoi chiedere di più?",
                    "Price"=> "6.30",
                    'Visible'=> 1,
                    'id_restaurant' => '8',
                ],
                [
                    "Name"=> "ROASTER CHICKEN BURGER",
                    "Image"=> "https://www.burgerking.it/prodotti/pollo/roaster-chicken/index_files/banner_prodotti_1440x640_copy.png",
                    "Description"=> "Panino sfizioso, caratterizzato dalla presenza della salsa Roasted Onion, cremosa e gustosa con un ricco sapore di cipolle arrosto, riesce a esaltare benissimo tutti gli altri ingredienti che accompagna fresca rucola, fette di pomodoro, cipole fritte, salsa BBQ, croccanti fette di bacon, cheddar e gustosa carne di pollo croccante.",
                    "Price"=> "9.10",
                    'Visible'=> 1,
                    'id_restaurant' => '8',
                ],
                [
                    "Name"=> "CRUNCHICKEN",
                    "Image"=> "https://www.burgerking.it/site/assets/files/8802859/1440x640.jpg",
                    "Description"=> "Pollo croccante, pomodoro, lattuga e doppia maionese, racchiusi in un morbido pane al mais.Vieni a provare il nostro nuovo Crunchicken.Un pollo così non l'hai mai sentito!",
                    "Price"=> "7.00",
                    'Visible'=> 1,
                    'id_restaurant' => '8',
                ],
                [
                    "Name"=> "INSALATA MISTA",
                    "Image"=> "https://www.burgerking.it/site/assets/files/2151/frontend_field_insalata_mista_1440x640.png",
                    "Description"=> "Insalata Mista, il piatto perfetto per chi vuole un contorno da abbinare al panino! L'abbinamento con il soncino, i pomodorini, i delicati petali di parmigiano reggiano e il mais contribuiscono a rendere qusta insalta super appetitosa!",
                    "Price"=> "8.20",
                    'Visible'=> 1,
                    'id_restaurant' => '8',
                ],
                [
                    "Name"=> "KING NUGGETS",
                    "Image"=> "https://www.burgerking.it/site/assets/files/135974/copertina.jpg",
                    "Description"=> "Tenerezza e croccantezza insieme? Se pensi che sia impossibile, non hai ancora provato i nuovi King Nuggets®! Deliziose pepite di pollo morbido e delicato con una panatura ancora più croccante e gustosa. Ogni morso sarà davvero unico.",
                    "Price"=> "6.10",
                    'Visible'=> 1,
                    'id_restaurant' => '8',
                ],
                [
                    "Name"=> "ONION RINGS",
                    "Image"=> "https://www.burgerking.it/site/assets/files/2053/onion-rings.jpg",
                    "Description"=> "Qui si chiude il cerchio per tutti i fan degli anelli di cipolla/. Immergili in una salsa e gustali. Oppure sgranocchia prima l'impanatura dorata e poi la cipolla. Esattamente come vuoi!",
                    "Price"=> "5.50",
                    'Visible'=> 1,
                    'id_restaurant' => '8',
                ],
                [
                    "Name"=> "OREO® SHAKE",
                    "Image"=> "https://www.burgerking.it/site/assets/files/8348642/oreo_website_prodotto_1440x640_2.png",
                    "Description"=> "I biscotti Oreo si fanno in mille pur di essere abbracciati dal cremoso gusto del gelato con aroma di vaniglia.E con una punta di panna montata sarà un incontro indimenticabile.",
                    "Price"=> "3.50",
                    'Visible'=> 1,
                    'id_restaurant' => '8',
                ],
                [
                    "Name"=> "SUNDAE FRAGOLA",
                    "Image"=> "https://www.burgerking.it/site/assets/files/2291/sundae_fragola_1440_x_640.jpg",
                    "Description" => "Delizioso gelato con aroma di vaniglia con sciroppo di fragola. Una combinazione tradizionale, intramontabile.",
                    "Price"=> "3.10",
                    'Visible'=> 1,
                    'id_restaurant' => '8',
                ],

        // Menù ristorante 9
                [
                    "Name"=>"Tender Crispy + Tender O.R.",
                    "Image"=>"https://media.imagonist.com/products/products/295_view_it.png?v=1691494754",
                    "Description"=>"Bucket con 2 croccantenerissimi Tender Crispy e 2 Tender Original Recipe, preparati rigorosamente con il mix segreto di 11 erbe e spezie del Colonnello Sanders. Perfetto per una persona. Provalo anche in versione Menu medio o grande con bibita e contorno a scelta. Goditi il Free Refill illimitato!",
                    "Price"=>"11.20",
                    'Visible'=> 1,
                    "id_restaurant"=>'9',
                ],
                [
                    "Name"=>"Colonel's Burger",
                    "Image"=>"https://media.imagonist.com/products/products/360_view_it.png?v=1694073104",
                    "Description"=>"Tutti i segreti del Colonnello, in un unico panino! Un tenero filetto di pollo con panatura Original Recipe realizzata con il mix segreto di 11 erbe e spezie, accompagnato da soffice Pan Brioche, maionese, formaggio, insalata, pomodoro e salsa Original. Scopri anche la versione Double, con due filetti Original, e raddoppia il gusto della tradizione!",
                    "Price"=>"9.80",
                    'Visible'=> 1,
                    "id_restaurant"=>'9',
                ],
                [
                    "Name"=>"Tender Crispy",
                    "Image"=>"https://media.imagonist.com/products/products/279_view_it.png?v=1691497255",
                    "Description"=>"Non perderti i deliziosi Tender Crispy di KFC filetti di Pollo dalla doppia infarinatura croccanti fuori e teneri dentro! Prova nella porzione da 4 pezzi o anche nel Bucket Tender da 10 pezzi. Li trovi anche nella versione Menu medio o grande con bibita e contorno per un pasto completo. Una volta provati non potrai più farne a meno.",
                    "Price"=>"3.50",
                    'Visible'=> 1,
                    "id_restaurant"=>'9',
                ],
                [
                    "Name"=>"Grilled Chicken",
                    "Image"=>"https://media.imagonist.com/products/products/359_view_it.png?v=1694077675",
                    "Description"=>"Non solo fritto. Il Pollo KFC è irresistibile anche grigliato. Pane soffice con il sesamo, 2 filetti di pollo grigliati, formaggio, doppio strato di maionese, fresca insalata e pomodoro. E se vuoi esagerare, aggiungi una fetta di bacon e una di formaggio. Puoi provarlo anche nella versione Menu medio o grande, con bibita e contorno a scelta.",
                    "Price"=>"8.40",
                    'Visible'=> 1,
                    "id_restaurant"=>'9',
                ],
                [
                    "Name"=>"Kentucky Cheese and Bacon",
                    "Image"=>"https://media.imagonist.com/products/products/348_view_it.png?v=1694073246",
                    "Description"=>"Una deliziosa novità, per i veri amanti del bacon. Lasciati tentare da un delizioso filetto di pollo con panatura Original Recipe, avvolto in un morbido Pan Brioche con doppio bacon croccante, maionese, formaggio e la cremosità della salsa al formaggio. Tutto il gusto KFC, all’ennesima potenza. Scegli la versione Double, con due filetti Original, e raddoppia il godimento!",
                    "Price"=>"7.30",
                    'Visible'=> 1,
                    "id_restaurant"=>'9',
                ],
                [
                    "Name"=>"Box Meal Zinger",
                    "Image"=>"https://media.imagonist.com/products/products/355_view_it.png?v=1694066660",
                    "Description"=>"Hai una passione per il piccante? Questo Box Meal fa per te! Goditi un panino Zinger, delizioso filetto di Pollo con panatura Hot & Spicy, insieme a 2 Tender Crispy, 1 Patatina, 1 Bibita e 1 salsa a scelta. Scegli la versione che preferisci, media o grande!",
                    "Price"=>"12.50",
                    'Visible'=> 1,
                    "id_restaurant"=>'9',
                ],
                [
                    "Name"=>"Cheese Shots",
                    "Image"=>"https://media.imagonist.com/products/products/288_view_it.png?v=1691497346",
                    "Description"=>"Prova i nostri irresistibili 'Cheese Shots'! Questi bocconcini di formaggio Emmental impanati e fritti sono un vero e proprio tripudio di gusto. La loro croccantezza ti conquisterà al primo morso, mentre l'interno filante ti regalerà un'esplosione di sapore. Ideali da condividere con gli amici come aperitivo o da gustare come contorno alternativo al tuo Bucket o menù preferito.",
                    "Price"=>"4.00",
                    'Visible'=> 1,
                    "id_restaurant"=>'9',
                ],
                [
                    "Name"=>"Pop Corn Chicken",
                    "Image"=>"https://media.imagonist.com/products/products/300_view_it.png?v=1688391881",
                    "Description"=>"Delizia il palato con i nostri teneri snack di Pollo. Questi gustosi spuntini sono perfetti per soddisfare la tua voglia di qualcosa di extra. Ma attenzione, quando li assaggi in compagnia, diventano un'esperienza imperdibile da condividere!",
                    "Price"=>"5.60",
                    'Visible'=> 1,
                    "id_restaurant"=>'9',
                ],
                [
                    "Name"=>"Krunchy",
                    "Image"=>"https://media.imagonist.com/products/products/301_view_it.png?v=1693556676",
                    "Description"=>"Se sei un amante del tenero croccante, non puoi perderti questo panino! Il nostro inimitabile Tender Crispy con la sua crosta dorata e irresistibile, è racchiuso in un morbido panino arricchito con semi di sesamo e accompagnato da una deliziosa combinazione di maionese e ketchup. E se vuoi rendere l'esperienza ancora più gustosa, puoi aggiungere una fetta di formaggio cheddar!",
                    "Price"=>"4.50",
                    'Visible'=> 1,
                    "id_restaurant"=>'9',
                ],
                [
                    "Name"=>"Snack Box Hot Wings",
                    "Image"=>"https://media.imagonist.com/products/products/286_view_it.png?v=1691497332",
                    "Description"=>"2 piccantissime Hot Wings, 1 porzione grande di patatine e lo snack è servito… disponibile in formato ready to go per gustarlo dove e come vuoi!",
                    "Price"=>"4.20",
                    'Visible'=> 1,
                    "id_restaurant"=>'9',
                ],

    // Menù ristorante 10
                [
                    "Name" => "Spaghetti pistacchio e gamberi",
                    "Image" =>"https://www.giusinaincucina.com/wp-content/uploads/2021/05/spaghetti-gamberoni-e-pesto-di-pistacchi.jpeg",
                    "Description"=> "Spaghetti artigianali con pesto di pistacchi e gamberi",
                    "Price"=> "25.00",
                    'Visible'=> 1,
                    'id_restaurant' => '10',
                ],
                [
                    "Name"=> "Lasagna",
                    "Image"=> "https://www.antoniettapolcaro.it/wp-content/uploads/2022/02/Lasagna-alla-napoletana_2022-scaled.jpg",
                    "Description"=> "Lasagna classica, cucinata secondo la tradizione napoletana!",
                    "Price"=> "13.00",
                    'Visible'=> 1,
                    'id_restaurant' => '10',
                ],
                [
                    "Name"=> "Rigatoni alla Carbonara",
                    "Image"=> "https://d15j9y5wlusr11.cloudfront.net/filer_public/5a/88/5a880300-87a7-4109-9780-6a07cad68575/recipe.jpg",
                    "Description"=> "Rigatoni con carbocrema e guanciale",
                    "Price"=> "15.00",
                    'Visible'=> 1,
                    'id_restaurant' => '10',
                ],
                [
                    "Name"=> "Rigatoni cacio e pepe",
                    "Image"=> "https://www.piuricette.it/wp-content/uploads/2022/11/rigatoni-cacio-e-pepe-1016x1024.jpeg",
                    "Description"=> "Rigatoni con crema di pecorino e pepe",
                    "Price"=> "12.00",
                    'Visible'=> 1,
                    'id_restaurant' => '10',
                ],
                [
                    "Name"=> "Pappardelle ai funghi porcini e salsiccia",
                    "Image"=> "https://www.chefstefanobarbato.com/ita/wp-content/uploads/2018/03/tagliatelle_funghi_e_salsiccia_pres.jpg",
                    "Description"=> "Pappardelle artigianali con sugo di salsiccia e funghi porcini!",
                    "Price"=> "15.00",
                    'Visible'=> 1,
                    'id_restaurant' => '10',
                ],
                [
                    "Name"=> "Pennette speck e noci",
                    "Image"=> "https://www.lospicchiodaglio.it/img/ricette/pastaspecknoci.jpg",
                    "Description"=> "Pennette rigate con speck e noci.",
                    "Price"=> "14.00",
                    'Visible'=> 1,
                    'id_restaurant' => '10',
                ],
                [
                    "Name"=> "Risotto alla milanese",
                    "Image"=> "https://cdn.cook.stbm.it/thumbnails/ricette/116/116036/hd750x421.jpg",
                    "Description"=> "Risotto con zafferano",
                    "Price"=> "17.00",
                    'Visible'=> 1,
                    'id_restaurant' => '10',
                ],
                [
                    "Name"=> "Cotoletta alla Milanese",
                    "Image"=> "https://www.tavolartegusto.it/wp/wp-content/uploads/2022/05/Cotoletta-alla-milanese.jpg",
                    "Description"=> "Cotoletta di carne servita con patatine fritte e verdura.",
                    "Price"=> "15.00",
                    'Visible'=> 1,
                    'id_restaurant' => '10',
                ],
                [
                    "Name"=> "Spezzatino con piselli",
                    "Image"=> "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2018/11/spezzatino-con-piselli/jcr:content/imagePreview.img10.jpg/1543233803718.jpg",
                    "Description"=> "Spezzatino di Manzo a lenta cottura servito con piselli",
                    "Price"=> "20.00",
                    'Visible'=> 1,
                    'id_restaurant' => '10',
                ],
                [
                    "Name"=> "Acqua Naturale",
                    "Image"=> "https://lnx.savia.it/80-home_default/acqua-naturale-1-litro.jpg",
                    "Description"=> "Bottiglia di acqua naturale da 1L",
                    "Price"=> "3.00",
                    'Visible'=> 1,
                    'id_restaurant' => '10',
                ],
            ]
        ];

        foreach ($plates['plates'] as $plate) {

            $newPlate = new Plate();

            $newPlate->name = $plate['Name'];

            $newPlate->image = $plate["Image"];
            $newPlate->description = $plate["Description"];
            $newPlate->price = $plate["Price"];
            $newPlate->visible = $plate['Visible'];
            $newPlate->slug = Str::of("$newPlate->id " . $newPlate->name)->slug('-');
            $newPlate->id_restaurant = $plate['id_restaurant'];
            $newPlate->save();

            $newPlate->slug = Str::of($newPlate->name)->slug('-');
            $newPlate->save();
        }
    }
}
